### ISSUE TITLE
Building fails - doesn't generate png files properly

### ISSUE THREAD

**Issue by htbrown** [ful1e5/BreezeX_Cursor#14]
Hi there,

I've gone to build these cursors to make a slightly larger variant for my use and have hit a bit of a roadblock. When running `make unix` on Linux, regardless of flags and variables, it errors and fails.

The output is as follows:
```
make[1]: Entering directory '/home/haydenbrown/temp/BreezeX_Cursor/bitmapper'
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 12.59s.
yarn run v1.22.10
$ npx ts-node src/index.ts
Generating bitmaps for BreezeX-Dark
 ==> Saving X_cursor ...
Done in 5.12s.
make[1]: Leaving directory '/home/haydenbrown/temp/BreezeX_Cursor/bitmapper'
make[1]: Entering directory '/home/haydenbrown/temp/BreezeX_Cursor/builder'
Requirement already satisfied: clickgen in /root/.local/lib/python3.10/site-packages (1.1.9)
Requirement already satisfied: Pillow>=8.1.1 in /usr/lib64/python3.10/site-packages (from clickgen) (8.3.2)
Getting 'BreezeX-Dark' bitmaps ready for build...
Traceback (most recent call last):
  File "/home/haydenbrown/temp/BreezeX_Cursor/builder/build.py", line 93, in <module>
    config = get_config(
  File "/home/haydenbrown/temp/BreezeX_Cursor/builder/src/configure.py", line 51, in get_config
    png_provider = PNGProvider(bitmaps_dir)
  File "/root/.local/lib/python3.10/site-packages/clickgen/util.py", line 72, in __init__
    raise FileNotFoundError(
FileNotFoundError: '*.png' files not found in '/home/haydenbrown/temp/BreezeX_Cursor/builder/../bitmaps/BreezeX-Dark'
Getting 'BreezeX-Light' bitmaps ready for build...
Traceback (most recent call last):
  File "/home/haydenbrown/temp/BreezeX_Cursor/builder/build.py", line 93, in <module>
    config = get_config(
  File "/home/haydenbrown/temp/BreezeX_Cursor/builder/src/configure.py", line 51, in get_config
    png_provider = PNGProvider(bitmaps_dir)
  File "/root/.local/lib/python3.10/site-packages/clickgen/util.py", line 68, in __init__
    for f in sorted(self.bitmaps_dir.iterdir()):
  File "/usr/lib64/python3.10/pathlib.py", line 1015, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '../bitmaps/BreezeX-Light'
Getting 'BreezeX-Black' bitmaps ready for build...
Traceback (most recent call last):
  File "/home/haydenbrown/temp/BreezeX_Cursor/builder/build.py", line 93, in <module>
    config = get_config(
  File "/home/haydenbrown/temp/BreezeX_Cursor/builder/src/configure.py", line 51, in get_config
    png_provider = PNGProvider(bitmaps_dir)
  File "/root/.local/lib/python3.10/site-packages/clickgen/util.py", line 68, in __init__
    for f in sorted(self.bitmaps_dir.iterdir()):
  File "/usr/lib64/python3.10/pathlib.py", line 1015, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '../bitmaps/BreezeX-Black'
make[1]: *** [Makefile:25: build_unix] Error 1
make[1]: Leaving directory '/home/haydenbrown/temp/BreezeX_Cursor/builder'
make: *** [Makefile:15: unix] Error 2
```

Have I just done something silly here?

Thanks.

**Comment by ful1e5** [comment]
Try `make clean` followed by `make unix`.

**Comment by htbrown** [comment]
I've recently had to reinstall my system so I'm not sure if the error will occur or be the same now, but I'll try your suggestion on this new machine. Thanks.

**Comment by htbrown** [comment]
Yeah it's working now, thanks.
